server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Iason09/config-server      # 配置Git仓库的地址
          username: Iason                                    # Git仓库的账号
          password: 520551CPR                                # Git仓库的密码
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: 119.27.166.15
    port: 5672
    username: Iason
    password: wwy383059893
encrypt:
  keyStore:
    location: classpath:/config-server.jks # jks文件的路径
    password: elephant               # storepass
    alias: dog                # alias
    secret: dinosaur                # keypass