server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Iason09/config-server      # 配置Git仓库的地址
          username: Iason09                                  # Git仓库的账号
          password: 520551Cpr                                # Git仓库的密码
#    bus:
#      trace:
#        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: 119.27.166.15
    port: 5672
    username: Iason
    password: '{cipher}AQByxzICdTFK9+k6Ep0hDomssXFb1rB6Vik73tpKEOwd6dx/v8MLjHIDjBSF516yI1v9jMl+4yqBw+sF+GcwuGEUkJEHikAZbpC4Yb2Qbyxiy5G7xUWXoO9Nn+qvSvEjDREIHqmUxuEf5QGTRSesiu+HrZHIQM7/FQkpqWZpwWD5mNzGF6EBySa7ERygesIlvqxy0QzH5OgOs9dvAyeUxrbotWsmEWVd/dkuu7rgc+ZBoLQLacE1wi5ndMYCEYFz+088PGbJhFYTkLDCVpu3fPleB6j8RgYeDc0MYOf6AKy2wYLPrtUv5oihb9Xj4eiwPBZMe2lh+3tRFjPtS+JFeIT5n/64B+RroqyeQHYKHrc+rQicVDT6nTEUMbIWWuoCRDI='
#    password: wwy383059893
